<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-Q8RUKJP2" failures="4" tests="8" name="TestA" time="0.862" errors="0" timestamp="2020-11-16T18:40:20 IST">
  <testcase classname="testRunners.test" name="test1" time="0.004"/>
  <testcase classname="testRunners.test" name="test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testRunners.test.test2(test.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="testRunners.test" name="test3" time="0.0"/>
  <testcase classname="testRunners.test" name="test4" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testRunners.test.test4(test.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="testRunners.test" name="test5" time="0.001"/>
  <testcase classname="testRunners.test" name="test6" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testRunners.test.test6(test.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- test6 -->
  <testcase classname="testRunners.test" name="test7" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testRunners.test.test7(test.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test7 -->
  <testcase classname="testRunners.test" name="test8" time="0.001"/>
</testsuite> <!-- TestA -->
